version: '1.0'
stages:
  - checkout   
  - plan
  - confirm apply
  - apply
steps:
  main_clone:
    title: Cloning main repository...
    stage: checkout
    type: git-clone
    repo: 'rajhansh1994/anz_ec2'
    revision: main
    git: github      
  DeployWithTerraform:
    image: hashicorp/terraform:1.0.8
    title: Deploying Terraform plan
    stage: plan
    commands:
      - terraform init
      - terraform plan
  confirm apply:
    type: pending-approval
    title: confirm apply 
    timeout:
    duration: 2
    finalState: approved
    timeUnit: minutes
    when:
      branch:
        only: [ main ]
  Terraform apply:
    image: hashicorp/terraform:1.0.8
    title: Deploying Terraform apply
    stage: apply
    commands:
      - terraform apply --auto-approve
      
